name: flutter_newbie
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  dio:
  retrofit: ^4.4.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_gen_runner:
  flutter_svg:
  flutter_lints: ^5.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  json_serializable: ^6.9.4
  freezed: ^3.0.4
  

flutter:

  uses-material-design: true

  assets:
    - assets/icons/


flutter_gen:
  integrations:
    flutter_svg: true
